### ISSUE TITLE
Error with Capistrano 3

### ISSUE THREAD

**Issue by AliHichem** [richdynamix/capistrano-ghostinspector#9]
Hi @richdynamix ,

This tool looks awesome but I can't get it to work with capistrano 3, I get this error when I run "cap -T"
```
set :giconfig = YAML::load(File.read("gi_config.yaml"))
```
Any ideas ? Thanks

**Comment by richdynamix** [comment]
Unfortunately it was only developed on Capistrano 2. I am not sure how much work would be involved to upgrade it. I would accept a PR though :)

**Comment by AliHichem** [comment]
This is unfortunate but I appreciate the fast response though !
I'll try to create some custom tasks to work with cap 3 (because I kind need it), it will be some raw  pieces of code but I may give a PR a try. 

Good day !
